apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.11.1
spec:
  # 关键修改：开启双栈优先
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv4
  - IPv6
  # 类型保持 LoadBalancer (K3s 会启动 svclb pod 来绑定节点 IP)
  type: LoadBalancer
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 8008        # 外部通过 IPv4/IPv6 访问的端口
    targetPort: http  # 容器内部端口
    # nodePort: 30165 # 建议注释掉，让 K8s 自动分配，避免冲突。如果你强制需要固定 NodePort 可取消注释
  - name: https
    appProtocol: https
    protocol: TCP
    port: 4443        # 外部通过 IPv4/IPv6 访问的端口
    targetPort: https
    # nodePort: 31763 # 同上